<a href="https://colab.research.google.com/github/cahyogadhang/cahyogadhang-2025-KECERDASAN-BUATAN-TI-1B/blob/main/jobsheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operasi matematika menggunakan python

## Mendapatkan nilai minimum dan maksimum

In [ ]:
x = min(5, 10, 25)
y = max(6, 12, 18)
print("x =",x,"y =",y)

x = 5 y = 18


## Mendapatkan nilai absolut

In [ ]:
x = abs(-7.25)
print("x =",x)

x = 7.25


## Mendapatkan nilai pangkat

In [ ]:
import math
x = math.pow(4, 3)
print("x =",x)

x = 64.0


## Mendapatkan nilai akar

In [ ]:
import math
x = math.sqrt(64)
print("x =",x)

x = 8.0


## Mendapatkan nilai pembulatan

In [ ]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)
print("x =",x,"y =",y)

x = 2 y = 1


## Mendapatkan nilai konstanta (PI)

In [ ]:
import math
x = math.pi
print("x =",x)

x = 3.141592653589793


# Menggunakan Fungsi MATH

In [ ]:
import math

def contoh_penggunaan_math():
    sudut_rad = math.pi / 2
    print(f"math.sin({sudut_rad}) = {math.sin(sudut_rad)}")
    print(f"math.cos({sudut_rad}) = {math.cos(sudut_rad)}")
    print(f"math.tan({sudut_rad}) = {math.tan(sudut_rad)}\n")

    angka = 10
    print(f"math.log({angka}) = {math.log(angka)}")
    print(f"math.log10({angka}) = {math.log10(angka)}\n")

    x = 0.5
    print(f"math.log1p({x}) = {math.log1p(x)}\n")

    print(f"math.log2({angka}) = {math.log2(angka)}\n")

    print(f"math.log10(100) = {math.log10(100)}\n")

    radian = math.pi
    print(f"math.degrees({radian}) = {math.degrees(radian)}\n")

    p1 = (1, 2)
    p2 = (4, 6)
    print(f"math.dist({p1}, {p2}) = {math.dist(p1, p2)}\n")

    n = 5
    print(f"math.factorial({n}) = {math.factorial(n)}\n")

    print(f"math.fmod(17, 5) = {math.fmod(17, 5)}\n")

    print(f"math.isnan(math.nan) = {math.isnan(math.nan)}")
    print(f"math.isnan(3.14) = {math.isnan(3.14)}\n")

    print(f"math.gamma(5) = {math.gamma(5)}\n")

    print(f"math.perm(5, 2) = {math.perm(5, 2)}")

if __name__ == "__main__":
    contoh_penggunaan_math()


math.sin(1.5707963267948966) = 1.0
math.cos(1.5707963267948966) = 6.123233995736766e-17
math.tan(1.5707963267948966) = 1.633123935319537e+16

math.log(10) = 2.302585092994046
math.log10(10) = 1.0

math.log1p(0.5) = 0.4054651081081644

math.log2(10) = 3.321928094887362

math.log10(100) = 2.0

math.degrees(3.141592653589793) = 180.0

math.dist((1, 2), (4, 6)) = 5.0

math.factorial(5) = 120

math.fmod(17, 5) = 2.0

math.isnan(math.nan) = True
math.isnan(3.14) = False

math.gamma(5) = 24.0

math.perm(5, 2) = 20


# Operasi matriks dan vektor dengan python

## Membuat matriks di pyhon

In [ ]:
import numpy as np
A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

print("hasil =",A+B)

hasil = [[110  90  40]
 [ 60  50  40]]


## Melakukan operasi dot product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

print("hasil =",np.dot(A, B))

hasil = 2025


## Melakukan operasi cross product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

print("Hasil =",np.cross(A, B))

Hasil = [-305 -110  350]


# TUGAS PRAKTIKUM

## Nomor 1


In [3]:
import numpy as np

A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

AB = np.dot(A, B)
print("a. A x B:\n", AB)

BC = np.dot(B, C)
print("b. B x C:\n", BC)

a. A x B:
 [[7 2]
 [4 2]]
b. B x C:
 [[ 0  2  3]
 [-3  1  3]]


## Nomor 2

In [ ]:
import math

# Menghitung 6!
faktorial_6 = math.factorial(6)
print("a. 6! =", faktorial_6)

# Menghitung (8! / 5!)
faktorial_8 = math.factorial(8)
faktorial_5 = math.factorial(5)
hasil = faktorial_8 / faktorial_5
print("b. 8! / 5! =", hasil)

a. 6! = 720
b. 8! / 5! = 336.0


## Nomor 3

In [1]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

dot_AB = np.dot(A, B)

cross_AB = np.cross(A, B)

print("Panjang (norma) Vektor A =", panjang_A)
print("Panjang (norma) Vektor B =", panjang_B)
print("Hasil A · B =", dot_AB)
print("Hasil A × B =", cross_AB)

Panjang (norma) Vektor A = 9.1104335791443
Panjang (norma) Vektor B = 12.409673645990857
Hasil A · B = 58
Hasil A × B = [ 24  79 -51]
